In [1]:
import cv2
import numpy as np

In [2]:
# 把lena 512*512图像灰度级逐级递减8-1显示
img = cv2.imread("Resource/lena.bmp", flags=cv2.IMREAD_GRAYSCALE)
print(img)

cv2.imshow("Image", img)
cv2.waitKey(0)

[[137 137 137 ... 148 130  99]
 [137 137 137 ... 148 130  99]
 [137 137 137 ... 148 130  99]
 ...
 [ 18  18  27 ...  73  68  62]
 [ 22  22  32 ...  70  71  74]
 [ 22  22  32 ...  70  71  74]]


-1

In [3]:
# 可以改变图片大小的堆叠函数，参考https://github.com/murtazahassan/Learn-OpenCV-in-3-hours
def stackImages(scale, imgArray):
    rows = len(imgArray)
    cols = len(imgArray[0])
    rowsAvailable = isinstance(imgArray[0], list)
    width = imgArray[0][0].shape[1]
    height = imgArray[0][0].shape[0]
    if rowsAvailable:
        for x in range ( 0, rows):
            for y in range(0, cols):
                if imgArray[x][y].shape[:2] == imgArray[0][0].shape [:2]:
                    imgArray[x][y] = cv2.resize(imgArray[x][y], (0, 0), None, scale, scale)
                else:
                    imgArray[x][y] = cv2.resize(imgArray[x][y], (imgArray[0][0].shape[1], imgArray[0][0].shape[0]), None, scale, scale)
                if len(imgArray[x][y].shape) == 2: imgArray[x][y]= cv2.cvtColor( imgArray[x][y], cv2.COLOR_GRAY2BGR)
        imageBlank = np.zeros((height, width, 3), np.uint8)
        hor = [imageBlank]*rows
        hor_con = [imageBlank]*rows
        for x in range(0, rows):
            hor[x] = np.hstack(imgArray[x])
        ver = np.vstack(hor)
    else:
        for x in range(0, rows):
            if imgArray[x].shape[:2] == imgArray[0].shape[:2]:
                imgArray[x] = cv2.resize(imgArray[x], (0, 0), None, scale, scale)
            else:
                imgArray[x] = cv2.resize(imgArray[x], (imgArray[0].shape[1], imgArray[0].shape[0]), None,scale, scale)
            if len(imgArray[x].shape) == 2: imgArray[x] = cv2.cvtColor(imgArray[x], cv2.COLOR_GRAY2BGR)
        hor= np.hstack(imgArray)
        ver = hor
    return ver

In [9]:
# 四舍五入取整
# img7 = np.array(np.around(img / 2) * 2, dtype=np.uint8)
# img6 = np.array(np.around(img / 4) * 4, dtype=np.uint8)
# img5 = np.array(np.around(img / 8) * 8, dtype=np.uint8)
# img4 = np.array(np.around(img / 16) * 16, dtype=np.uint8)
# img3 = np.array(np.around(img / 32) * 32, dtype=np.uint8)
# img2 = np.array(np.around(img / 64) * 64, dtype=np.uint8)
# img1 = np.array(np.around(img / 128) * 128, dtype=np.uint8)

# 截断取整
img7 = np.array(np.floor(img / 2) * 2, dtype=np.uint8)
img6 = np.array(np.floor(img / 4) * 4, dtype=np.uint8)
img5 = np.array(np.floor(img / 8) * 8, dtype=np.uint8)
img4 = np.array(np.floor(img / 16) * 16, dtype=np.uint8)
img3 = np.array(np.floor(img / 32) * 32, dtype=np.uint8)
img2 = np.array(np.floor(img / 64) * 64, dtype=np.uint8)
img1 = np.array(np.floor(img / 128) * 128, dtype=np.uint8)

imgStack = stackImages(0.5, ([img, img7, img6, img5], [img4, img3, img2, img1]))
cv2.imshow("ImgStack", imgStack)
cv2.waitKey(0)

-1

In [5]:
# 计算图像均值和方差
imgOriginal = cv2.imread("Resource/lena.bmp", flags=cv2.IMREAD_UNCHANGED)
mean, stddev = cv2.meanStdDev(imgOriginal)
print(mean)
print(stddev)

[[99.05121613]]
[[52.87751733]]


In [7]:
stddev[0] * stddev[0]

array([2796.03183888])

In [53]:
# zoom(resize) 图像
img = cv2.imread("Resource/lena.bmp")
imgNear = cv2.resize(imgOriginal, (2048, 2048), interpolation=cv2.INTER_NEAREST)  # 近邻插值
imgBilinear = cv2.resize(imgOriginal, (2048, 2048), interpolation=cv2.INTER_LINEAR)  # 双线性插值
imgBicubic = cv2.resize(imgOriginal, (2048, 2048), interpolation=cv2.INTER_CUBIC)  # 双三次插值

cv2.imwrite("Output/imgNear.bmp", imgNear)
cv2.imwrite("Output/imgBilinear.bmp", imgBilinear)
cv2.imwrite("Output/imgBicubic.bmp", imgBicubic)

True

In [2]:
# 图像shearing后resize至2048*2048
lena = cv2.imread("Resource/lena.bmp", cv2.IMREAD_UNCHANGED)
elain = cv2.imread("Resource/elain1.bmp", cv2.IMREAD_UNCHANGED)

shearMatrix = np.float32([[1, 1.5, 0], [0, 1, 0], [0, 0, 1]])
shearedLenaNear = cv2.warpPerspective(lena, shearMatrix, dsize=(2048, 2048), flags=cv2.INTER_NEAREST)
shearedElainNear = cv2.warpPerspective(elain, shearMatrix, dsize=(2048, 2048), flags=cv2.INTER_NEAREST)
cv2.imwrite("Output/shearedLenaNear.bmp", shearedLenaNear)
cv2.imwrite("Output/shearedElainNear.bmp", shearedElainNear)

shearedLenaLinear = cv2.warpPerspective(lena, shearMatrix, dsize=(2048, 2048), flags=cv2.INTER_LINEAR)
shearedElainLinear = cv2.warpPerspective(elain, shearMatrix, dsize=(2048, 2048), flags=cv2.INTER_LINEAR)
cv2.imwrite("Output/shearedLenaLinear.bmp", shearedLenaLinear)
cv2.imwrite("Output/shearedElainLinear.bmp", shearedElainLinear)

shearedLenaCubic = cv2.warpPerspective(lena, shearMatrix, dsize=(2048, 2048), flags=cv2.INTER_CUBIC)
shearedElainCubic = cv2.warpPerspective(elain, shearMatrix, dsize=(2048, 2048), flags=cv2.INTER_CUBIC)
cv2.imwrite("Output/shearedLenaCubic.bmp", shearedLenaCubic)
cv2.imwrite("Output/shearedElainCubic.bmp", shearedElainCubic)

True

In [3]:
# 图像旋转
def rotate(image, angle, rotPoint=None):
    (height, width) = image.shape[:2]

    if rotPoint is None:
        rotPoint = (width//2, height//2)

    rotMat = cv2.getRotationMatrix2D(rotPoint, angle, scale=1.0)
    dimensions = [width, height]
    # dimensions = [2048, 2048]

    return cv2.warpAffine(image, rotMat, dimensions)


rotatedLena = rotate(lena, 30)
rotatedLenaNear = cv2.resize(rotatedLena, (2048, 2048), interpolation=cv2.INTER_NEAREST)
rotatedLenaLinear = cv2.resize(rotatedLena, (2048, 2048), interpolation=cv2.INTER_LINEAR)
rotatedLenaCubic = cv2.resize(rotatedLena, (2048, 2048), interpolation=cv2.INTER_CUBIC)
cv2.imwrite("Output/rotatedLenaNear.bmp", rotatedLenaNear)
cv2.imwrite("Output/rotatedLenaLinear.bmp", rotatedLenaLinear)
cv2.imwrite("Output/rotatedLenaCubic.bmp", rotatedLenaCubic)

rotatedElain = rotate(elain, 30)
rotatedElainNear = cv2.resize(rotatedElain, (2048, 2048), interpolation=cv2.INTER_NEAREST)
rotatedElainLinear = cv2.resize(rotatedElain, (2048, 2048), interpolation=cv2.INTER_LINEAR)
rotatedElainCubic = cv2.resize(rotatedElain, (2048, 2048), interpolation=cv2.INTER_CUBIC)
cv2.imwrite("Output/rotatedElainNear.bmp", rotatedElainNear)
cv2.imwrite("Output/rotatedElainLinear.bmp", rotatedElainLinear)
cv2.imwrite("Output/rotatedElainCubic.bmp", rotatedElainCubic)

True